[package]
name = "pandemaniac_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
petgraph = "0.6.3"
serde_json = "1.0.70"
rayon = "1.5.1"